# Monitoring location map

## Read site locations
```{r, site-locs}
sites=dataRetrieval::readNWISsite(siteNumbers=subset(site_list, SiteType %in% c("Elevation gauge","Causeway breach","Lake", "Lake, DBL"))$SiteNumber)
sites=merge(sites,site_list, by.x=c("site_no","station_nm"), by.y=c("SiteNumber","SiteName"))
```

## Build site map
```{r, build-site-map}
sites=within(sites, {
    LatitudeMeasure=dec_lat_va
    LongitudeMeasure=dec_long_va
    MonitoringLocationTypeName=SiteType
    MonitoringLocationIdentifier=site_no
    MonitoringLocationName=station_nm
})
site_map=wqTools::buildMap(sites=sites, plot_polys=F, search="") %>% 
        leaflet::fitBounds(lng1=min(sites$LongitudeMeasure), lng2=max(sites$LongitudeMeasure), lat1=min(sites$LatitudeMeasure), lat2=max(sites$LatitudeMeasure)) %>% 
        leaflet::removeMeasure()
```

```{r, site-map, echo=F, fig.cap="Site location map."}
site_map
```



## Build AU map

```{r, build-au-map}
library(leaflet)
aus=c("UT-L-16020310-002_00","UT-L-16020310-001_00","UT-L-16020310-003_00","UT-L-16020310-004_00")
gsl_au_poly=subset(wqTools::au_poly, ASSESS_ID %in% aus)
bbox=sf::st_bbox(gsl_au_poly)

au_map=wqTools::baseMap() %>% clearGroup("Assessment units") %>% 
	addPolygons(data=gsl_au_poly, group="Assessment units",fillOpacity = 0.1, layerId=gsl_au_poly$polyID,weight=3,color="orange", options = pathOptions(pane = "au_poly"),
		label=(gsl_au_poly$AU_NAME)
	) %>%
	showGroup("Assessment units") %>% 
	fitBounds(-112.9889834316615, 40.65976503522424, -111.9315494464152, 41.717990192304775)
```
