---
title: "Great Salt Lake Salinity Dashboard"
output: 
  flexdashboard::flex_dashboard:
    theme: yeti
    orientation: rows
    css: extra.css
    source_code: "https://github.com/utah-dwq/GSL-dashboard"
    social: menu
---

```{r, init}
#setwd('C:\\Users\\jvander\\Documents\\R\\gsldb\\dashboard')
load('sal_db_figs.Rdata') 
```

# Salinity
Sidebar {.sidebar data-width=300}
-------------------------------------

### Salinity in Great Salt Lake
Salinity is measured... All data from NWIS. 

**Gilbert Bay salinity** is characterized by the average of open water Gilbert Bay surface samples in the last 120 days.  
<br>
**Gunnison Bay salinity** is the average of measurements from last 120 days at the Gunnison Bay near Saline, UT gauge.


Row
-----------------------------------------------------------------------
### 
```{r}
sa_sal_gauge
```

### 
```{r}
na_sal_gauge
```


Row
-----------------------------------------------------------------------

### Time series
```{r}
sal_ts
```



# Elevation
Sidebar {.sidebar data-width=300}
-------------------------------------


Row
-----------------------------------------------------------------------
### 
```{r}
sa_elev_gauge
```

### 
```{r}
na_elev_gauge
```


Row
-----------------------------------------------------------------------

### Time series
```{r}
elev_ts
```




# Breach flows
Sidebar {.sidebar data-width=300}
-------------------------------------

Row
-----------------------------------------------------------------------
### Breach flows
```{r}
breach_disch_ts
```

Row
-----------------------------------------------------------------------
### 
```{r}
breach_disch_hist
```




# Gilbert Bay salt pools
Sidebar {.sidebar data-width=300}
-------------------------------------


Row
-----------------------------------------------------------------------
###
```{r}
salt_mass_plot
```


# Site map
Sidebar {.sidebar data-width=300}
-------------------------------------


Row
-----------------------------------------------------------------------
###
```{r}
site_map
```



# Slider map
Sidebar {.sidebar data-width=300}
-------------------------------------

Row
-----------------------------------------------------------------------
###
```{r, out.extra='style="border: none;"', out.width='100%'}
# see: https://github.com/NUKnightLab/juxtapose#html-implementation
knitr::include_url("images/slider.html", height="100%")
```



<style>
body:after {
content: url(www/deq_dwq_logo.png);
position: fixed;
bottom: 0.5em;
left: 0.5em;
}
</style>








